// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsjUPOEqTKNPzH1ORufoHb-ncznBv24do',
    appId: '1:176097130446:web:cee1de3e0a78d642e8dd9f',
    messagingSenderId: '176097130446',
    projectId: 'fertilizer-recommendatio-73585',
    authDomain: 'fertilizer-recommendatio-73585.firebaseapp.com',
    databaseURL: 'https://fertilizer-recommendatio-73585-default-rtdb.firebaseio.com',
    storageBucket: 'fertilizer-recommendatio-73585.appspot.com',
    measurementId: 'G-4Z3HFEPV5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDThrn2rvat0SjgOwAMefkj80tEgFQyvPg',
    appId: '1:176097130446:android:d42d157eb292f516e8dd9f',
    messagingSenderId: '176097130446',
    projectId: 'fertilizer-recommendatio-73585',
    databaseURL: 'https://fertilizer-recommendatio-73585-default-rtdb.firebaseio.com',
    storageBucket: 'fertilizer-recommendatio-73585.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgy-QMcJ12-NlfD5nDeVENENWIwrBjvww',
    appId: '1:176097130446:ios:324b3568079799c4e8dd9f',
    messagingSenderId: '176097130446',
    projectId: 'fertilizer-recommendatio-73585',
    databaseURL: 'https://fertilizer-recommendatio-73585-default-rtdb.firebaseio.com',
    storageBucket: 'fertilizer-recommendatio-73585.appspot.com',
    iosClientId: '176097130446-5vp7a6087dhs3n1or27j5mp7u67570sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fertilizerRecommendationSystem',
  );
}
